version: '3.3'

services:
  db:
    image: mariadb:10.1.41
    # build: './mysql_build'
    container_name: mariadb_web
    secrets:
      - source: db
        target: db.env
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    volumes:
      - ./all_db_dump_file.sql:/docker-entrypoint-initdb.d/all_db_dump_file.sql
    ports:
      - "3306:3306"
  web:
    # image: php:7.2-apache
    build: './php_build'
    image: php7-apache2:latest
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8080:80"
    stdin_open: true
    tty: true

secrets:
  db:
    file: ./credentials/db.env
